@startuml
skinparam svgDimensionStyle false
hide footbox
participant "KenyaEMR 1" as EMR1
participant "KenyaEMR 2" as EMR2
participant "Data Mediator" as Data
participant "CQF Ruler" as CQL
participant "Report Generator" as Report 

activate CQL
loop Copy Data to FHIR/CQL Server
  activate Data
  activate EMR1
  Data -> EMR1: Query for FHIR resource updates\n**GET ///<Resource>//**\n  **?_lastUpdated=gtYYYY-MM-DD**
  EMR1 -> Data: Return FHIR resources
  deactivate EMR1
  Data -> CQL: Save FHIR resources to server\n**PUT ///<Resource>/////<id>//**\nor\n**POST ///<Bundle>//**
  CQL -> Data: Return confirmation or error
  deactivate Data
end

loop Copy Data to FHIR/CQL Server
  activate Data
  activate EMR2
  Data -> EMR2: Query for FHIR resource updates\n**GET ///<Resource>//**\n  **?_lastUpdated=gtYYYY-MM-DD**
  EMR2 -> Data: Return FHIR resources
  deactivate EMR2
  Data -> CQL: Save FHIR resources to server\n**PUT ///<Resource>/////<id>//**\nor\n**POST ///<Bundle>//**
  CQL -> Data: Return confirmation or error
  deactivate Data
end

activate Report
opt Update indicator resources
  Report -> CQL: Save updated Measure, Library, Terminology resources\n**PUT ///<Resource>/////<id>//**\nor\n**POST ///<Bundle>//**
  CQL -> Report: Return confirmation or error
end

Report -> CQL: Evaluate measure for the period\n**GET /Measure/TXCURR/$evaluate-measure**\n  **?periodStart=YYYY-MM-DD&periodEnd=YYYY-MM-DD**
CQL -> Report: Return MeasureReport
deactivate Report
deactivate CQL

@enduml
