### @host = http://localhost:8080/matchbox/fhir
@host = https://test.ahdis.ch/matchbox/fhir


### Convert FML to StructureMap
POST {{host}}/StructureMap/$convert HTTP/1.1
Content-Type: text/fhir-mapping
Accept: application/fhir+json


< ./HIVObservationHIVCondition.map


### Put it
PUT {{host}}/StructureMap/HIVObservationHIVCondition HTTP/1.1
Content-Type: application/fhir+json
Accept: application/fhir+JSON


< ./StructureMap-HIVObservationHIVCondition.json


### Verify StructureMap is created
GET {{host}}/StructureMap/HIVObservationHIVCondition HTTP/1.1
Accept: application/fhir+JSON



### Transforms
POST {{host}}/StructureMap/$transform?source=https://path-global-health.github.io/MERindicators/StructureMap/HIVObservationHIVCondition
Accept: application/fhir+json;fhirVersion=4.0
Content-Type: application/fhir+json;fhirVersion=4.0
 
< ./test-data1.json

